//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Icoltrans.Sigelo.Entity.Seguridad;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SeguridadModelo : DbContext
    {
        public SeguridadModelo()
            : base("name=SeguridadModelo")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<OpcionPerfil> ObtenerOpcionesUsuario(string vcUsuario, Nullable<byte> tyIdModulo)
        {
            var vcUsuarioParameter = vcUsuario != null ?
                new ObjectParameter("vcUsuario", vcUsuario) :
                new ObjectParameter("vcUsuario", typeof(string));
    
            var tyIdModuloParameter = tyIdModulo.HasValue ?
                new ObjectParameter("tyIdModulo", tyIdModulo) :
                new ObjectParameter("tyIdModulo", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OpcionPerfil>("ObtenerOpcionesUsuario", vcUsuarioParameter, tyIdModuloParameter);
        }
    }
}
