del /q /f /s Icoltrans.Sigelo.Comunes\bin\*.*
del /q /f /s Icoltrans.Sigelo.Data\bin\*.*
del /q /f /s Icoltrans.Sigelo.Rules.Maestros\bin\*.*
del /q /f /s Icoltrans.Sigelo.Rules.Nomina\bin\*.*
del /q /f /s Icoltrans.Sigelo.Rules.Produccion\bin\*.*
del /q /f /s Icoltrans.Sigelo.Rules.Satrack\bin\*.*
del /q /f /s Icoltrans.Sigelo.Web.Host\bin\*.*
del /q /f /s Icotrans.Sigelo.Rules.Vehiculos\bin\*.*
del /q /f /s Sigelo.Client\bin\*.*
del /q /f /s Icoltrans.Sigelo.Comunes\obj\*.*
del /q /f /s Icoltrans.Sigelo.Data\obj\*.*
del /q /f /s Icoltrans.Sigelo.Rules.Maestros\obj\*.*
del /q /f /s Icoltrans.Sigelo.Rules.Nomina\obj\*.*
del /q /f /s Icoltrans.Sigelo.Rules.Produccion\obj\*.*
del /q /f /s Icoltrans.Sigelo.Rules.Satrack\obj\*.*
del /q /f /s Icoltrans.Sigelo.Web.Host\obj\*.*
del /q /f /s Icotrans.Sigelo.Rules.Vehiculos\obj\*.*
del /q /f /s Sigelo.Client\obj\*.*
pause
