//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Icoltrans.Sigelo.Entity.Vehiculos;
    
    public partial class VehiculosModelo : DbContext
    {
        public VehiculosModelo()
            : base("name=VehiculosModelo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ruta> Rutas { get; set; }
        public DbSet<Satelital> Satelital { get; set; }
        public DbSet<VehiculoSatelital> VehiculosSatelital { get; set; }
    }
}
