//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Win.Vehiculos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GoogleMapsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GoogleMapsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Icoltrans.Sigelo.Win.Vehiculos.Resources.GoogleMapsResource", typeof(GoogleMapsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html &quot;-//W3C//DTD XHTML 1.0 Strict//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd&quot;&gt; 
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt; 
        ///&lt;head&gt; 
        ///	&lt;title&gt;&lt;/title&gt; 
        ///	&lt;script type=&quot;text/javascript&quot; src=&quot;http://maps.google.com/maps?file=api&amp;v=2&amp;key=ABQIAAAAONGnFL0kcCdyn5RUHzY_mBRd4ruDrR6G_7td499m6HnvNnWrUhQMTo0N5R0CRkmVPONFKqYMqY6_oA&quot;&amp;sensor=false&quot;&gt;&lt;/script&gt;
        ///	&lt;script type=&quot;text/javascript&quot;&gt;
        ///	
        ///		var map = null;
        ///		
        ///		var marcadores = [];
        ///				
        ///		var point = null;
        ///		
        ///		var cargado = false;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IFrame {
            get {
                return ResourceManager.GetString("IFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.sonaravl.com/AVLServer/qmap.aspx?user=srendon&amp;pwd=s1stemas&amp;placa=&amp;alertas={0}&amp;cmd=flota.
        /// </summary>
        internal static string IFrame2 {
            get {
                return ResourceManager.GetString("IFrame2", resourceCulture);
            }
        }
    }
}
