//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Win.Vehiculos.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Icoltrans.Sigelo.Win.Vehiculos.Resources.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cambia el nombre de la caravana sin afectar su ubicación actual o cualquier otra característica..
        /// </summary>
        internal static string CambioNombre {
            get {
                return ResourceManager.GetString("CambioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear una caravana con las mismas características de la caravana original, a excepción de la ruta, la cual se selecciona en esta pantalla. Finaliza la caravana original e inicia el recorrido de la nueva caravana.  La asignación de escoltas y refuerzos se realiza por la respectiva opción de menú..
        /// </summary>
        internal static string CambioRuta {
            get {
                return ResourceManager.GetString("CambioRuta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para los tráileres de la compañía, se permite seleccionar un nuevo carnet con el fin de hacer cambio de cabezote..
        /// </summary>
        internal static string CanbioCarnet {
            get {
                return ResourceManager.GetString("CanbioCarnet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuando una caravana tiene dos o más vehículos, permite crear una nueva caravana con el nombre y la ruta especificados en esta pantalla.  Seleccione con doble clic los vehículos que quiere asignar a esta nueva caravana.  Ninguna de las dos listas puede quedar totalmente vacía.  La asignación de escoltas y refuerzos se realiza por las correspondientes opciones de menú..
        /// </summary>
        internal static string DividirCaravana {
            get {
                return ResourceManager.GetString("DividirCaravana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v.
        /// </summary>
        internal static string LetraVehiculo {
            get {
                return ResourceManager.GetString("LetraVehiculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe seleccionar una caravana.
        /// </summary>
        internal static string SeleccionarCaravana {
            get {
                return ResourceManager.GetString("SeleccionarCaravana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string Separador {
            get {
                return ResourceManager.GetString("Separador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \r\n--------------------\r\n.
        /// </summary>
        internal static string SeparadorObservacion {
            get {
                return ResourceManager.GetString("SeparadorObservacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta.
        /// </summary>
        internal static string TituloAlerta {
            get {
                return ResourceManager.GetString("TituloAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleccione una caravana existente para unir todos los vehículos de la caravana original a la caravana seleccionada.  La caravana original se dará por terminada.  La asignación de escoltas y refuerzos se realiza por las opciones de menú correspondientes..
        /// </summary>
        internal static string UnirCaravana {
            get {
                return ResourceManager.GetString("UnirCaravana", resourceCulture);
            }
        }
    }
}
