//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Vehiculos
{
    using System;
    using System.Runtime.Serialization;
    
    [DataContract]
    public sealed partial class EstadoVehiculo
    {
        [DataMember]
    	public int Id { get; set; }
        [DataMember]
    	public short fsmIdEstadoVehiculo { get; set; }
        [DataMember]
    	public string fvcDescripcion { get; set; }
        [DataMember]
    	public bool fbtProgramable { get; set; }
        [DataMember]
    	public int fmsIdRazonEstadoVehiculo { get; set; }
        [DataMember]
    	public Nullable<int> Razon { get; set; }
    }
}
