//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Vehiculos
{
    using System;
    using System.Runtime.Serialization;
    
    [DataContract]
    public sealed partial class Refuerzo
    {
        [DataMember]
    	public int Id { get; set; }
        [DataMember]
    	public decimal Identificacion { get; set; }
        [DataMember]
    	public string Nombre { get; set; }
        [DataMember]
    	public string Email { get; set; }
        [DataMember]
    	public string Direccion { get; set; }
        [DataMember]
    	public string Ubicacion { get; set; }
        [DataMember]
    	public string Usuario { get; set; }
        [DataMember]
    	public System.DateTime UltimaModificacion { get; set; }
    }
}
