//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Vehiculos
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract]
    public sealed partial class Ruta
    {
        [DataMember]
    	public int Id { get; set; }
        [DataMember]
    	public string Descripcion { get; set; }
        [DataMember]
    	public string IdUbicacionOrigen { get; set; }
        [DataMember]
    	public string IdUbicacionDestino { get; set; }
        [DataMember]
    	public byte MinutosReporte { get; set; }
        [DataMember]
    	public byte MinutosAlerta { get; set; }
        [DataMember]
    	public byte Urbana { get; set; }
        [DataMember]
    	public string Usuario { get; set; }
        [DataMember]
    	public System.DateTime LastUpdate { get; set; }
        [DataMember]
    	public byte[] Timestamp { get; set; }
    }
}
