//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Vehiculos
{
    using System;
    using System.Runtime.Serialization;

    [DataContract]
    public sealed partial class Seguimiento
    {
        [DataMember]
    	public System.Guid fidCaravana { get; set; }
        [DataMember]
    	public string fvcDescripcion { get; set; }
        [DataMember]
    	public int finIdRuta { get; set; }
        [DataMember]
    	public string origen { get; set; }
        [DataMember]
    	public string destino { get; set; }
        [DataMember]
    	public System.DateTime fdtSalida { get; set; }
        [DataMember]
    	public int ftyMinutosReporte { get; set; }
        [DataMember]
    	public int ftyMinutosAlerta { get; set; }
        [DataMember]
    	public int fbtUrbana { get; set; }
        [DataMember]
    	public Nullable<int> finUltimoPunto { get; set; }
        [DataMember]
    	public string fvcUltimoPunto { get; set; }
        [DataMember]
    	public string fvcEstado { get; set; }
        [DataMember]
    	public System.DateTime fdtUltimoPunto { get; set; }
        [DataMember]
    	public Nullable<int> finSiguientePunto { get; set; }
        [DataMember]
    	public string fvcSiguientePunto { get; set; }
        [DataMember]
    	public System.DateTime fdtSiguientePunto { get; set; }
        [DataMember]
    	public double frlDiferencia { get; set; }
        [DataMember]
    	public string ruta { get; set; }
        [DataMember]
    	public Nullable<short> ftyEstReporte { get; set; }
        [DataMember]
    	public Nullable<short> ftyEstAlerta { get; set; }
        [DataMember]
    	public int Vehiculos { get; set; }
        [DataMember]
    	public string ftxObservacion { get; set; }
        [DataMember]
        public string Satelital { get; set; }
        [DataMember]
        public string URLSatelital { get; set; }
        [DataMember]
        public string UsuarioSatelital { get; set; }
        [DataMember]
        public string ClaveSatelital { get; set; }
    }
}
