//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Vehiculos
{
    using System;
    using System.Runtime.Serialization;
    
    [DataContract]
    public sealed partial class VehiculoPorSalir
    {
        [DataMember]
    	public int finNumeroCarnet { get; set; }
        [DataMember]
    	public string fvcPlaca { get; set; }
        [DataMember]
    	public short fsmModelo { get; set; }
        [DataMember]
    	public string Completa { get; set; }
        [DataMember]
    	public decimal fnuManifiesto { get; set; }
        [DataMember]
    	public string fvcDescripcion { get; set; }
        [DataMember]
    	public string Trailer { get; set; }
        [DataMember]
    	public string fvcNombre { get; set; }
        [DataMember]
    	public string COrigen { get; set; }
        [DataMember]
    	public string CDestino { get; set; }
        [DataMember]
    	public string Conductor { get; set; }
        [DataMember]
    	public Nullable<decimal> IdentidadConductor { get; set; }
        [DataMember]
    	public Nullable<int> fbtEnCaravana { get; set; }
        [DataMember]
    	public string fvcUsuario { get; set; }
        [DataMember]
    	public System.DateTime fdtLastUpd { get; set; }
        [DataMember]
    	public bool Prioridad { get; set; }
        [DataMember]
    	public string Destinos { get; set; }
        [DataMember]
    	public string Centro { get; set; }
        [DataMember]
    	public Nullable<System.Guid> fidCaravana { get; set; }
        [DataMember]
    	public string Telefono { get; set; }
        [DataMember]
    	public string Property { get; set; }
    }
}
