//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Vehiculos
{
    using System;
    using System.Runtime.Serialization;
    
    [DataContract]
    public sealed partial class Vehiculo
    {
        [DataMember]
    	public string Placa { get; set; }
        [DataMember]
    	public string Carroceria { get; set; }
        [DataMember]
    	public string Chasis { get; set; }
        [DataMember]
    	public string Color { get; set; }
        [DataMember]
    	public string Complemento { get; set; }
        [DataMember]
    	public string De { get; set; }
        [DataMember]
    	public byte Ejes { get; set; }
        [DataMember]
    	public Nullable<byte> GPS { get; set; }
        [DataMember]
    	public Nullable<decimal> Manifiesto { get; set; }
        [DataMember]
    	public string Marca { get; set; }
        [DataMember]
    	public short Modelo { get; set; }
        [DataMember]
    	public string Motor { get; set; }
        [DataMember]
    	public float Peso { get; set; }
        [DataMember]
    	public bool Prioridad { get; set; }
        [DataMember]
    	public string Tipo { get; set; }
        [DataMember]
    	public string Vinculacion { get; set; }
        [DataMember]
    	public float Volumen { get; set; }
        [DataMember]
    	public byte VinculacionId { get; set; }
    }
}
