//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Vehiculos
{
    using System;
    using System.Runtime.Serialization;
    
    [DataContract]
    public sealed partial class VehiculoCaravana
    {
        public VehiculoCaravana()
        {
            this.NumeroCarnet = 0;
            this.Conductor = new Conductor();
            this.Vehiculo = new Vehiculo();
        }
    
        [DataMember]
    	public string CiudadesRecorrido { get; set; }
        [DataMember]
    	public Nullable<int> NumeroCarnet { get; set; }
        [DataMember]
    	public Nullable<decimal> Manifiesto { get; set; }
        [DataMember]
    	public bool Prioridad { get; set; }
        [DataMember]
    	public System.Guid Id { get; set; }
        [DataMember]
    	public string NombreCaravana { get; set; }
        [DataMember]
    	public string Origen { get; set; }
        [DataMember]
    	public string Destino { get; set; }
        [DataMember]
    	public bool NoCambiar { get; set; }
        [DataMember]
    	public string Estado { get; set; }
    
        [DataMember]
    	public Conductor Conductor { get; set; }
        [DataMember]
    	public Vehiculo Vehiculo { get; set; }
    }
}
