//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Icoltrans.Sigelo.Entity.Nomina;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class NominaModelo : DbContext
    {
        public NominaModelo()
            : base("name=NominaModelo")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Escolta1> EmpleadosGrupoCargo(Nullable<byte> tyIdGrupoCargo, Nullable<short> smIDSucursal)
        {
            var tyIdGrupoCargoParameter = tyIdGrupoCargo.HasValue ?
                new ObjectParameter("tyIdGrupoCargo", tyIdGrupoCargo) :
                new ObjectParameter("tyIdGrupoCargo", typeof(byte));
    
            var smIDSucursalParameter = smIDSucursal.HasValue ?
                new ObjectParameter("smIDSucursal", smIDSucursal) :
                new ObjectParameter("smIDSucursal", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Escolta1>("EmpleadosGrupoCargo", tyIdGrupoCargoParameter, smIDSucursalParameter);
        }
    }
}
