//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Seguridad
{
    using System;
    using System.Runtime.Serialization;
    
    [DataContract]
    public sealed partial class OpcionPerfil
    {
        [DataMember]
    	public string Identificador { get; set; }
        [DataMember]
    	public string Descripcion { get; set; }
        [DataMember]
    	public string Href { get; set; }
        [DataMember]
    	public bool Crear { get; set; }
        [DataMember]
    	public bool Modificar { get; set; }
        [DataMember]
    	public bool Eliminar { get; set; }
        [DataMember]
    	public bool Confirmacion { get; set; }
        [DataMember]
    	public System.Guid IdOpcion { get; set; }
    }
}
