//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Produccion
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract]
    public sealed partial class Operacion
    {
        [DataMember]
    	public System.Guid fidOperacion { get; set; }
        [DataMember]
    	public int finIdLote { get; set; }
        [DataMember]
    	public int finIdServicioNegocio { get; set; }
        [DataMember]
    	public System.DateTime fdtFecha { get; set; }
        [DataMember]
    	public Nullable<System.Guid> fidPuntoEntregaOrigen { get; set; }
        [DataMember]
    	public Nullable<System.Guid> fidPuntoEntregaDestino { get; set; }
        [DataMember]
    	public Nullable<System.DateTime> fdtCompromisoCliente { get; set; }
        [DataMember]
    	public Nullable<System.DateTime> fdtCitaEntrega { get; set; }
        [DataMember]
    	public Nullable<decimal> fnuRemision { get; set; }
        [DataMember]
    	public string fvcCartaPorte { get; set; }
        [DataMember]
    	public string fvcFactura { get; set; }
        [DataMember]
    	public Nullable<System.DateTime> fdtFechaFactura { get; set; }
        [DataMember]
    	public string fvcPedido { get; set; }
        [DataMember]
    	public Nullable<System.DateTime> fdtFechaPedido { get; set; }
        [DataMember]
    	public string fvcOrdenCompra { get; set; }
        [DataMember]
    	public Nullable<System.DateTime> fdtFechaOrdenCompra { get; set; }
        [DataMember]
    	public string fvcDespacho { get; set; }
        [DataMember]
    	public Nullable<System.DateTime> fdtFechaDespacho { get; set; }
        [DataMember]
    	public float frlPeso { get; set; }
        [DataMember]
    	public short fsmIdUnidadMedidaPeso { get; set; }
        [DataMember]
    	public float frlVolumen { get; set; }
        [DataMember]
    	public short fsmIdUnidadMedidaVolumen { get; set; }
        [DataMember]
    	public int finUnidades { get; set; }
        [DataMember]
    	public short fsmIdUnidadMedidaEmpaque { get; set; }
        [DataMember]
    	public float frlArea { get; set; }
        [DataMember]
    	public short fsmIdUnidadMedidaArea { get; set; }
        [DataMember]
    	public decimal fmoValor { get; set; }
        [DataMember]
    	public byte ftyEstado { get; set; }
        [DataMember]
    	public Nullable<byte> ftyFacturado { get; set; }
        [DataMember]
    	public string fvcUltimaUbicacion { get; set; }
        [DataMember]
    	public string fvcUltimaDocumento { get; set; }
        [DataMember]
    	public decimal fmoTarifa { get; set; }
        [DataMember]
    	public decimal fmoSeguro { get; set; }
        [DataMember]
    	public short fsmIdSucursal { get; set; }
        [DataMember]
    	public Nullable<int> finTipoNovedad { get; set; }
        [DataMember]
    	public Nullable<bool> fbtDirecto { get; set; }
        [DataMember]
    	public float frlKilos { get; set; }
        [DataMember]
    	public float frlMetros2 { get; set; }
        [DataMember]
    	public float frlMetros3 { get; set; }
        [DataMember]
    	public string fvcUsuario { get; set; }
        [DataMember]
    	public System.DateTime fdtLastUpd { get; set; }
        [DataMember]
    	public byte[] ftsTimestamp { get; set; }
    }
}
