//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Icoltrans.Sigelo.Entity.Produccion
{
    using System;
    using System.Runtime.Serialization;
    using System.Collections.Generic;
    
    [DataContract]
    public sealed partial class PuntoEntrega2
    {
        [DataMember]
    	public System.Guid fidPuntoEntrega { get; set; }
        [DataMember]
    	public string fvcDescripcion { get; set; }
        [DataMember]
    	public string fvcDireccion { get; set; }
        [DataMember]
    	public string fvcTelefono { get; set; }
        [DataMember]
    	public string fvcCodigoEDI { get; set; }
        [DataMember]
    	public string fnuManifiesto { get; set; }
        [DataMember]
    	public Nullable<int> fsmOrden { get; set; }
        [DataMember]
    	public Nullable<double> frlKilos { get; set; }
        [DataMember]
    	public Nullable<int> finUnidades { get; set; }
    }
}
